src/Entity/Award.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AwardRepository")
 */
class Award
{
    //const SERVER_PATH_TO_IMAGE_FOLDER = 'img/awards';

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $award_name;

    /**
     * @ORM\Column(type="text")
     */
    private $award_description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $award_image;

    /**
     * Unmapped property to handle file uploads
     */
    private $file;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAwardName(): ?string
    {
        return $this->award_name;
    }

    public function setAwardName(string $award_name): self
    {
        $this->award_name = $award_name;

        return $this;
    }

    public function getAwardDescription(): ?string
    {
        return $this->award_description;
    }

    public function setAwardDescription(string $award_description): self
    {
        $this->award_description = $award_description;

        return $this;
    }

    public function getAwardImage(): ?string
    {
        return $this->award_image;
    }

    /**
     * @param string|null $award_image
     *
     * @return $this
     */
    public function setAwardImage( ?string $award_image): self
    {
        $this->award_image = $award_image;

        return $this;
    }

    /**
     * @param UploadedFile $file
     */
    public function setFile(UploadedFile $file = null)
    {
        $this->file = $file;
    }

    /**
     * @return UploadedFile
     */
    public function getFile()
    {
        return $this->file;
    }


}

src/Form/AwardType.php
<?php

namespace App\Form;

use App\Entity\Award;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AwardType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('award_name', TextType::class)
            ->add('award_description', CKEditorType::class)
            ->add('file', FileType::class, [
//                'mapped'   => false,
                'required' => false
            ]);
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Award::class,
        ]);
    }
}

src/Controller/AwardController.php
<?php

namespace App\Controller;

use App\Entity\Award;
use App\Form\AwardType;
use App\Service\FileUploader;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AwardController extends AbstractController
{
    /** @var EntityManagerInterface */
    private $entityManager;

    /**
     * AwardController constructor.
     *
     * @param EntityManagerInterface $entityManager
     */
    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    /**
     * @Route("/award", name="award")
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $awards = $this
            ->getDoctrine()
            ->getRepository(Award::class)
            ->findAll();
        foreach ( $awards as $award) {
            $award->setAwardDescription(htmlspecialchars($award->getAwardDescription()));
        }
        return $this->render('award/index.html.twig', [
            'awards' => $awards,
            'title'  => 'Награды',
        ]);
    }

    /**
     * @Route("/award/new", name="award_new")
     *
     * @param Request $request
     *
     * @param FileUploader $fileUploader
     *
     * @return Response
     */
    public function new(Request $request, FileUploader $fileUploader)
    {
        $award = new Award();
        $form = $this->createForm(AwardType::class, $award);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
//            dd($award);
//            $file = $form['award_image']->getData();
            $fileName = $fileUploader->upload($award->getFile(), "/awards");
            $award->setAwardImage($fileName);

            $this->entityManager->persist($award);
            $this->entityManager->flush();
            $this->addFlash('success', 'new award has been created');

            return $this->redirectToRoute('award');
        }

        return $this->render('award/new.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/award/{id}", name="award_show")
     *
     * @param Award $award
     *
     * @return Response
     */
    public function show(Award $award): Response
    {
        return $this->render('award/show.html.twig', [
            'award' => $award,
            'title' => 'Награды'
        ]);
    }

    /**
     * @Route("/award/edit/{id}", name="award_edit")
     *
     * @param Request $request
     *
     * @param Award $award
     *
     * @param FileUploader $fileUploader
     *
     * @return Response
     */
    public function edit(Request $request, Award $award, FileUploader $fileUploader): Response
    {
        $form = $this->createForm(AwardType::class, $award);
        $form->handleRequest($request);

        //dd($form->getData());
        if ($form->isSubmitted() && $form->isValid()) {
            //$file = $form['award_image']->getData();
            if ($award->getFile()) {
                $fileName = $fileUploader->upload($award->getFile(), '/awards');
                $award->setAwardImage($fileName);
            }
            $this->entityManager->flush();
            $this->addFlash('success', 'selected award has been updated');

            return $this->redirectToRoute('award');
        }

        return $this->render('award/edit.html.twig', [
            'award' => $award,
            'form'  => $form->createView(),
        ]);
    }

    /**
     * @Route("/award/delete/{id}", name="award_delete")
     *
     * @param Award $award
     *
     * @return Response
     */
    public function delete(Award $award): Response
    {
        if (!$award) {
            throw $this->createNotFoundException(
                'No awards found'
            );
        }

        $this->entityManager->remove($award);
        $this->entityManager->flush();
        $this->addFlash('success', 'selected award has been deleted');

        return $this->redirectToRoute('award');
    }
}

templates/award/_form.html.twig
{% block form %}
        {{ form_start(form) }}
    <div style="margin-bottom: 1rem;">
        <div>
            <div>
                {{ form_errors(form.award_name) }}
            </div>
            <div>
                {{ form_label(form.award_name) }}
            </div>
            <div>
                {{ form_widget(form.award_name) }}
            </div>
            <small>{{ form_help(form.award_name) }}</small>
        </div>
        <div>
            <div>
                {{ form_errors(form.award_description) }}
            </div>
            <div>
                {{ form_label(form.award_description) }}
            </div>
            <div>
                {{ form_widget(form.award_description) }}
            </div>
            <small>{{ form_help(form.award_description) }}</small>
        </div>
        <div >
            <div>
                {{ form_errors(form.file) }}
            </div>
            <div>
                {{ form_label(form.file) }}
            </div>
            <div>
                {{ form_widget(form.file) }}
            </div>
            <small>{{ form_help(form.file) }}</small>
        </div>
        <div style="margin: 2em 0;">
            <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
        </div>
        {{ form_end(form) }}
    </div>

{% endblock form %}

templates/award/edit.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <h1>Edit News</h1>
    {{ include('award/_form.html.twig', {'button_label': 'Update'}) }}

    <a class="btn btn-primary" href="{{ path('award_delete', { id:award.id }) }}">Delete</a>
    <a class="btn btn-primary" href="{{ path('award') }}">Назад к списку</a>
{% endblock %}

templates/award/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ title }} {% endblock %}

{% block body %}
    <h1>{{ title }}</h1>
    <div class="list-group">
        {% for award in awards %}
            <div class="list-group-item">
                <div class="row">
                    <div class="col-4">
                        <a href="{{ path('award_show', {id: award.id}) }}">
                            <img src="{{ asset('img/awards/') ~ award.awardImage }}" alt="">
                        </a>
                    </div>
                    <div class="col-8">
                        <a href="{{ path('award_show', {id: award.id}) }}">
                            <h3>{{ award.awardName }}</h3>
                        </a>
                        <p>{{ award.awardDescription }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
        <a href="{{ path('award_new') }}">Create new</a>
    </div>
{% endblock %}

templates/award/new.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <h1>Create new Awards</h1>

    {{ include('award/_form.html.twig') }}

    <a href="{{ path('award') }}">back to list</a>
{% endblock %}

templates/award/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ title }}{% endblock %}

{% block body %}
    <h1>{{ award.awardName }}</h1>
    <div class="container-fluid row">
        <div class="col-4">
            <img src="{{ asset('img/awards/') ~ award.awardImage }}" alt="">
        </div>
        <div class="col-8">
            <span>
                {{ award.awardDescription }}
            </span>
        </div>
    </div>
    <a href="{{ path('award_edit', {id: award.id}) }}" class="card-link">Редактировать</a>
    <a href="{{ path('award') }}">Обратно к списку</a>

{% endblock %}